### ISSUE TITLE
针对于<=IE10的浏览器兼容

### ISSUE THREAD

**Issue by HeartCloud** [YDJ-FE/ts-react-webpack4#1]
你的思路很清晰，结构也合理！但是，你应该没有考虑浏览器兼容性，针对于<=IE10的浏览器怎么处理呢？

**Comment by jackple** [comment]
@HeartCloud 哪方面的兼容性呢

**Comment by jackple** [comment]
@HeartCloud IE10都不可以用? 把错误贴上来看看

**Comment by HeartCloud** [comment]
![image](https://user-images.githubusercontent.com/29745572/42742670-3b3d1e20-88ef-11e8-836f-dc6e4856e6a6.png)

**Comment by HeartCloud** [comment]
hi，朋友：
    刚测试你的demo，ie11都不能正常使用

**Comment by jackple** [comment]
@HeartCloud 不好意思, 忘了说mobx5之后的兼容性, 详看https://github.com/mobxjs/mobx#browser-support

**Comment by liwan11123123** [comment]
本来是用的angular 6写的pc 项目，结果要写手机端， 用这个写了几天发现不能<=11. 在想如何是好

**Comment by HeartCloud** [comment]
mobx5版本是不兼容低版浏览器的，可以考虑降级到mobx4的版本



ht1005cyh@163.com
 
发件人： liwan11123123
发送时间： 2018-10-03 20:01
收件人： YDJ-FE/ts-react-webpack
抄送： 胡挺; Mention
主题： Re: [YDJ-FE/ts-react-webpack] 针对于<=IE10的浏览器兼容 (#1)
本来是用的angular 6写的pc 项目，结果要写手机端， 用这个写了几天发现不能<=11. 在想如何是好

**Comment by liwan11123123** [comment]
可否给个 降级到mobx4的版本 的 方案呢？
降级过后是否需要改动源码的api？

**Comment by jackple** [comment]
@liwan11123123 mobx4、5的api是兼容的


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by liwan11123123** [comment]
![image](https://user-images.githubusercontent.com/43085718/46467883-7ea40100-c801-11e8-9a99-8fc1d89fb4f6.png)


我在降级到mobx 4.5.0 的时候出现了运行时的报错。有方式可以解决吗？

**Comment by liwan11123123** [comment]
顺便问下，有没有可以一起交流的群呢？

**Comment by jackple** [comment]
@liwan11123123 暂时没有相关的群.

对于上述的报错, 请修改https://github.com/YDJ-FE/ts-react-webpack/blob/008cc3a0f4dd357e8898184c624472975cc5938c/build/webpack.config.js#L26

因为`mobx4`并没有这个资源文件
