### ISSUE TITLE
idea scss cannot resolve file是如何解决的，运行打包均未出错

### ISSUE THREAD

**Issue by HeartCloud** [YDJ-FE/ts-react-webpack4#2]
![image](https://user-images.githubusercontent.com/29745572/42857016-8563ad2a-8a7a-11e8-9753-014729fce091.png)

**Comment by jackple** [comment]
@HeartCloud  配置https://github.com/YDJ-FE/ts-react-webpack4/blob/master/build/style-loaders.js#L7

**Comment by HeartCloud** [comment]
您好！以下是我的配置，可以正常运行和编译。但是webstorm会提示上述错误

const config = require('./config');
const {resolve} = require('./utils');

const sassLoader = {
    loader: 'sass-loader',
    options: {
        includePaths: [resolve('src/styles')]
    }
};

const lessLoader = {
    loader: 'less-loader',
    options: {
        javascriptEnabled: true,
        modifyVars: theme,
    }
};

const typingsForCssModulesLoaderConf = {
    loader: 'typings-for-css-modules-loader',
    options: {
        localIdentName: '[local]_[hash:base64:8]',
        modules: true,
        namedExport: true,
        camelCase: true,
        sass: true,
        sourceMap: false
    }
};

module.exports = [
    {
        test: /\.css$/,
        include: [resolve('node_modules')],
        use: [
            config.extractCss ? MiniCssExtractPlugin.loader : 'style-loader',
            'css-loader'
        ]
    },
    {
        test: /\.less/,
        include: [resolve('node_modules')],
        use: [
            config.extractCss ? MiniCssExtractPlugin.loader : 'style-loader',
            'css-loader',
            'postcss-loader',
            lessLoader
        ]
    },
    {
        test: /\.scss$/,
        include: [resolve('src')],
        use: [
            config.extractCss ? MiniCssExtractPlugin.loader : 'style-loader',
            typingsForCssModulesLoaderConf,
            sassLoader,
            {loader: 'postcss-loader'}
        ]
    }
];

**Comment by jackple** [comment]
@HeartCloud webstorm 不会认webpack的配置, 我没试过webstorm相关的配置, 刚刚google了一下, 社区上也有类似的问题, 比如https://stackoverflow.com/questions/21987225/webstorm-cannot-resolve-directory, 你可以自己查查, 忽略这种错误
